// <auto-generated />
namespace MeetupMsg.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class meetup001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(meetup001));
        
        string IMigrationMetadata.Id
        {
            get { return "201309181204481_meetup001"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
